import {getAllPublished} from "../lib/notion";
import Link from "next/link";
import Head from 'next/head'

// export async function getStaticProps() {
//     const data = await getAllPublished()
//
//     return {
//         props: {
//             posts: data,
//         },
//         revalidate: 60
//     };
// }

const Page = async ({posts}) => {
    const data = await getAllPublished()
    if (!posts) return <h1>No posts</h1>
    return (
        <div className="container">
            <Head>
                <title>My Blog</title>
                <meta name="description" content="Generated by create next app"/>
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <div className="main">
                <h1>Blog</h1>
                {data.map((post, index) => (
                    <section key={index}>
                        <div>
                            <h2>
                                <Link href={post.slug}>
                                    <a>{post.title}</a>
                                </Link>
                            </h2>
                            <div>
                                <div>{post.date}</div>
                                <p>{post.description}</p>
                            </div>
                        </div>
                    </section>
                ))
                }
            </div>
        </div>
    )
}

export default Page;



